spring:
  datasource:
    url: jdbc:mysql://localhost:3306/primary_education_system?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: rabiloo
    password: rabiloo
    tomcat:
      max-wait: 20000
      max-active: 150
      max-idle: 30
      log-abandoned: true
      remove-abandoned: false
      remove-abandoned-timeout: 60
      test-on-borrow: true
      validation-query: SELECT 1
  data:
    redis:
      repositories:
        enabled: false
  thymeleaf:
    mode: HTML
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy/MM/dd HH:mm
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 2000
        order_inserts: true
        order_update: true
    open-in-view: false
  mvc:
    favicon:
      enabled:true
    async:
      request-timeout: 5000
liquibase:
  enabled: true
  change-log: classpath:/liquibase/db-changelog-master.xml
  drop-first: false
server:
  port: 8080
google:
  maps:
    apiKey: AIzaSyCRBsUodSjnQ_n2xKV2zbuv_NvkXuWz_A4
  youtube:
    apiKey: AIzaSyDZTK99yYZa9HySJUmEeaz5H2vjjkYDWaY
isOnSendMailError: false
errorReportReceiver: xxx@gmail.com
application:
